(deftheme CrapCram
  "Created 2014-11-13.")

(custom-theme-set-faces
 'CrapCram
 '(cursor ((t (:background "dark gray"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#729fcf"))))
 '(highlight ((t (:background "light gray" :foreground "gray21"))))
 '(region ((t (:background "dim gray" :foreground "#e1e1e0"))))
 '(shadow
   ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50"))
    (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70"))
    (((class color) (min-colors 8) (background light)) (:foreground "green"))
    (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection
   ((((class color) (min-colors 88) (background light)) (:background "yellow1"))
    (((class color) (min-colors 88) (background dark)) (:background "SkyBlue4"))
    (((class color) (min-colors 16) (background light)) (:background "yellow"))
    (((class color) (min-colors 16) (background dark)) (:background "SkyBlue4"))
    (((class color) (min-colors 8)) (:foreground "black" :background "cyan"))
    (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "#ff4242"))))
 '(font-lock-builtin-face ((t (:foreground "#23d7d7"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "dark olive green" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#008b8b"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#00ede1" :slant oblique :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "DarkGoldenrod2" :weight bold))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#e67128"))))
 '(font-lock-type-face ((t (:foreground "#34cae2"))))
 '(font-lock-variable-name-face ((t (:foreground "medium sea green"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ff4242" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line) :inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#59e9ff"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#ed74cd" :inherit (link)))))
 '(fringe ((t (:background "gray12"))))
 '(header-line ((t (:box nil :foreground "#333333" :background "#e5e5e5" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#eeeeec" :background "#212931"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "#eeeeec" :background "#878787" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#000000" :background "#fcffad"))))
 '(isearch-fail
   ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1"))
    (((class color) (min-colors 88) (background dark)) (:background "red4"))
    (((class color) (min-colors 16)) (:background "red"))
    (((class color) (min-colors 8)) (:background "red"))
    (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "#338f86"))))
 '(match
   ((((class color) (min-colors 88) (background light)) (:background "yellow1"))
    (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3"))
    (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow"))
    (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue"))
    (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default
    ((t (:inherit nil :stipple nil :background "gray2" :foreground "pale goldenrod"
                  :inverse-video nil :box nil :strike-through nil :overline nil
                  :underline nil :slant normal :weight normal :height 113 :width normal
                  :foundry "unknown" :family "DejaVu Sans Mono")))))

(provide-theme 'CrapCram)
