(defvar mypackages '(org-drill-table yaxception ws-butler writegood-mode web-mode volatile-highlights undo-tree sr-speedbar speed-type smartparens smart-mode-line-powerline-theme powerline smart-mode-line rich-minority slime-company slime macrostep rainbow-mode rainbow-delimiters pyenv-mode py-autopep8 paredit ox-twbs ox-reveal org ox-pandoc ht ox-html5slide org-ref htmlize helm-bibtex biblio biblio-core hydra key-chord pdf-tools tablist org-projectile org-category-capture org-plus-contrib org-bullets mc-extras multiple-cursors matlab-mode magit ghub git-commit magit-popup with-editor linum-relative latex-unicode-math-mode latex-preview-pane latex-pretty-symbols latex-math-preview latex-extra julia-shell julia-mode jedi-direx jedi auto-complete direx indicators indent-guide iedit hlinum highlight-symbol highlight-parentheses highlight-indent-guides highlight-blocks highlight helm-swoop helm-rtags helm-org-rifle helm-mt multi-term helm-make projectile helm-gtags helm-google helm-git helm-flyspell helm-flymake helm-flycheck helm-dictionary helm-company helm-c-yasnippet helm-R helm helm-core async gnuplot-mode gnuplot function-args flymake-shell flymake-python-pyflakes flymake-easy flylisp flycheck-rtags flycheck-irony flycheck-cstyle flycheck-clangcheck flycheck pkg-info epl exec-path-from-shell ess-smart-underscore ess-smart-equals ess-R-data-view ess elpy find-file-in-project highlight-indentation dtrt-indent dictcc ivy csv-mode csv cpputils-cmake company-shell company-rtags rtags company-php ac-php-core php-mode xcscope popup company-math math-symbol-lists company-jedi jedi-core epc concurrent ctable python-environment deferred company-irony-c-headers company-irony irony company-c-headers company-bibtex parsebib company-auctex yasnippet auctex company-anaconda company anaconda-mode pythonic f dash cmake-project cmake-mode cmake-ide levenshtein clean-aindent-mode benchmark-init auto-virtualenv pyvenv s auto-dictionary anzu ))
              (unless package-archive-contents
                (package-refresh-contents))
              (setq pp '())
              (dolist (p package-archive-contents)
                      (push (car p) pp))
              (dolist (package mypackages)
                (unless (package-installed-p package)
                  (if (member package pp) (package-install package))))
