(defvar mypackages '(ess iedit magit php-mode r-autoyas rtags yasnippet-snippets anzu auto-dictionary auto-virtualenv benchmark-init clean-aindent-mode cmake-ide cmake-mode cmake-project company-anaconda anaconda-mode company-auctex company-bibtex company-c-headers company-irony company-irony-c-headers company-jedi company-math company-php ac-php-core company-rtags company-shell cpputils-cmake csv csv-mode dictcc dtrt-indent elpy ess-R-data-view ess-smart-equals ess-smart-underscore exec-path-from-shell find-file-in-project flycheck-clangcheck flycheck-cstyle flycheck-irony flycheck-rtags flylisp flymake-python-pyflakes flymake-shell flymake-easy function-args gnuplot gnuplot-mode helm-R ess helm-c-yasnippet helm-company helm-dictionary helm-flycheck flycheck helm-flymake helm-flyspell helm-git helm-google helm-gtags helm-make helm-mt helm-org-rifle helm-rtags helm-swoop highlight highlight-blocks highlight-indent-guides highlight-indentation highlight-parentheses highlight-symbol hlinum iedit indent-guide indicators irony jedi-direx direx jedi auto-complete jedi-core epc ctable concurrent julia-shell julia-mode latex-extra auctex latex-math-preview latex-pretty-symbols latex-preview-pane latex-unicode-math-mode levenshtein linum-relative magit git-commit ghub magit-popup math-symbol-lists matlab-mode mc-extras multi-term multiple-cursors org-bullets org-drill-table org-plus-contrib org-projectile org-category-capture org-ref key-chord hydra ivy helm-bibtex biblio biblio-core helm helm-core htmlize ox-html5slide ox-pandoc ht ox-reveal org ox-twbs paredit parsebib pdf-tools php-mode popup projectile pkg-info epl py-autopep8 pyenv-mode python-environment deferred pythonic f pyvenv rainbow-delimiters rainbow-mode rtags s slime-company company slime macrostep smart-mode-line-powerline-theme smart-mode-line rich-minority powerline smartparens dash speed-type sr-speedbar tablist undo-tree volatile-highlights web-mode with-editor async writegood-mode ws-butler xcscope yasnippet yaxception ))
                  (unless package-archive-contents
                    (package-refresh-contents))
                  (setq pp '())
                  (dolist (p package-archive-contents)
                          (push (car p) pp))
                  (dolist (package mypackages)
                    (unless (package-installed-p package)
                      (if (member package pp) (package-install package))))
